
/* 03/24/2015 */
insert into barangays(city_id,city,barangay)values
('5','AMLAN','Bio-os')
,('5','AMLAN','Jantiano')
,('5','AMLAN','Jugno')
,('5','AMLAN','Mag-abo')
,('5','AMLAN','Poblacion')
,('5','AMLAN','Silab')
,('5','AMLAN','Tambojangin')
,('5','AMLAN','Tandayag')
,('6','AYUNGON','Amdus')
,('6','AYUNGON','Anibong')
,('6','AYUNGON','Atabay')
,('6','AYUNGON','Awa-an')
,('6','AYUNGON','Ban-ban')
,('6','AYUNGON','Calagcalag')
,('6','AYUNGON','Candana-ay')
,('6','AYUNGON','Carol-an')
,('6','AYUNGON','Gomentoc')
,('6','AYUNGON','Inacban')
,('6','AYUNGON','Iniban')
,('6','AYUNGON','Jandalamanon')
,('6','AYUNGON','Kilaban')
,('6','AYUNGON','Lamigan')
,('6','AYUNGON','Maaslum')
,('6','AYUNGON','Mabato')
,('6','AYUNGON','Manogtong')
,('6','AYUNGON','Nabhang')
,('6','AYUNGON','Poblacion')
,('6','AYUNGON','Tambo')
,('6','AYUNGON','Tampocon I')
,('6','AYUNGON','Tampocon II')
,('6','AYUNGON','Tibyawan')
,('6','AYUNGON','Tiguib')
,('27','VALENCIA','Apolong')
,('27','VALENCIA','East Balabag')
,('27','VALENCIA','West Balabag')
,('27','VALENCIA','Balayagmanok')
,('27','VALENCIA','Balili')
,('27','VALENCIA','Balugo')
,('27','VALENCIA','Bongbong')
,('27','VALENCIA','Bong-ao')
,('27','VALENCIA','Calayugan')
,('27','VALENCIA','Cambucad')
,('27','VALENCIA','Dobdob')
,('27','VALENCIA','Jawa')
,('27','VALENCIA','Caidiocan')
,('27','VALENCIA','Liptong')
,('27','VALENCIA','Lunga')
,('27','VALENCIA','Malabo')
,('27','VALENCIA','Malaunay')
,('27','VALENCIA','Mampas')
,('27','VALENCIA','Palinpinon')
,('27','VALENCIA','North Poblacion')
,('27','VALENCIA','South Poblacion')
,('27','VALENCIA','Puhagan')
,('27','VALENCIA','Pulangbato')
,('27','VALENCIA','Sagbang')
;

insert into cities(city)values
('AMLAN'),('AYUNGON'),('BACONG'),('BAIS CITY'),('BASAY'),('CITY OF BAYAWAN'),('BINDOY'),('CANLAON CITY'),('DAUIN'),('DUMAGUETE CITY'),('CITY OF GUIHULNGAN'),('JIMALALUD'),('LA LIBERTAD'),('MABINAY'),('MANJUYOD'),('PAMPLONA'),('SAN JOSE'),('SANTA CATALINA'),('SIATON'),('SIBULAN'),('CITY OF TANJAY'),('TAYASAN'),('VALENCIA'),('VALLEHERMOSO'),('ZAMBOANGUITA')
;
